### ISSUE TITLE
Prefixing of favorites with '*' is not a good idea

### ISSUE THREAD

**Issue by dreadful-brain** [RedTartan04/rMbk2tree#1]
Very nice script, I tried it on windows with WSL (windows subsystem for linux) and it works quite well.
The only problem is, I had to disable prefixing favorites with '*' as this is a wildcard on windows and you cannot create files and folders, which contain '*' or '?' on this system.
Maybe you should use '#' instead of '*'

**Comment by RedTartan04** [comment]
Thanks for your interest and the note about the '\*'. I like the '\*' and I'd rather not make this a fully cross-platform script just because of the many limitations of Windows ;-) :-) (there are many more characters forbidden than on macOS; also reserved filenames).
With the flags and paths at the beginning, the users are already expected to edit the script to fit their needs, including the mac-specific icon.
So what if we put the prefix string into a constant at the beginning of the the script, too, and use that in line 120? This would make it easier to use whatever's the user's favorite favorite prefix :-)

**Comment by dreadful-brain** [comment]
Perfect!
I think handling this with a constant is the best approach.
